const { CodeBuilder } = require('./codeBuilder');
const { generateCreateFunction, collectComponentRefNames } = require('./domGenerator');
const { generateUpdateFunction } = require('./updateGenerator');
const { interceptAssignments, findReactiveMutations } = require('./assignmentInterceptor');
const { assertServerRenderable } = require('./serverGenerator');
const { generateHydrationFunction } = require('./hydrationGenerator');
const { VERSIONS } = require('../version.js');

/**
 * Wraps the parsed component into a single, importable Factory Closure.
 * @param {Object} astPayload - The Final Handoff Object (must include rawScript).
 * @param {Object} [options] - Generation options.
 * @param {boolean} [options.hydratable] - When true, the module additionally
 *   exports hydrateComponent(target, props, state), which adopts server-rendered
 *   markup instead of recreating it. Hydratable modules are restricted to the
 *   server-renderable component surface. Default generation is unchanged.
 * @returns {string} The final compiled JavaScript module.
 */
function generateComponent(astPayload, options = {}) {
  const hydratable = options.hydratable === true;
  if (hydratable) {
    // The hydration walk cannot adopt component tags or block constructs, so
    // hydratable modules are held to the same surface as the server target.
    assertServerRenderable(astPayload);
  }
  const builder = new CodeBuilder();
      const componentImports = astPayload.imports || [];
  const props = astPayload.props || [];

  // Prop bindings are parent-owned and read-only: any statement-level
  // mutation of a prop name inside the child script is a compile-time error.
  if (props.length > 0 && astPayload.rawScript) {
    const propMutations = findReactiveMutations(astPayload.rawScript, props.map((prop) => prop.name));
    if (propMutations.length > 0) {
      const first = propMutations[0];
      throw new SyntaxError(`Props are read-only: '${first.name}' cannot be assigned inside the component at ${first.line}:${first.column}.`);
    }
  }

  // Generated modules self-identify so artifacts stay traceable to the
  // compiler and contract versions that produced them.
  builder.add(`// Generated by Wizz ${VERSIONS.compiler} (component syntax ${VERSIONS.syntax}, generated output ${VERSIONS.output}). Edits will be overwritten.`);
  builder.add('');

      componentImports.forEach(({ name, source }) => {
            builder.add(`import ${name} from ${JSON.stringify(source.replace(/\.wizz$/, '.js'))};`);
      });
      if (componentImports.length > 0) builder.add('');

  // 1. Factory Function Signature. `props` carries the values the parent
  // passed to the component tag; missing keys fall back to declared defaults.
  // Hydratable modules route both public entries through one mountInstance
  // closure; the default emission is unchanged.
  if (hydratable) {
    builder.add('export default function mountComponent(target, props = {}) {')
          .indent()
          .add('return mountInstance(target, props, false, null);')
          .dedent()
          .add('}')
          .add('')
          .add('export function hydrateComponent(target, props = {}, state = null) {')
          .indent()
          .add('return mountInstance(target, props, true, state);')
          .dedent()
          .add('}')
          .add('')
          .add('function mountInstance(target, props, hydrate, state) {')
          .indent();
  } else {
    builder.add('export default function mountComponent(target, props = {}) {')
          .indent();
  }

      const reactiveVars = astPayload.script.filter(decl => decl.isReactive);

      builder.add('let isMounted = false;');
      builder.add('let isDestroyed = false;');
      builder.add('let batchScheduled = false;');
      builder.add('let pendingChanges = {};');
      builder.add('const mountHooks = [];');
      builder.add('const destroyHooks = [];');
      builder.add('function onMount(hook) { mountHooks.push(hook); }');
      builder.add('function onDestroy(hook) { destroyHooks.push(hook); }');
      builder.add('const trackedListeners = [];');
      builder.add('function trackListener(node, eventName, handler) {')
                    .indent()
                    .add('node.addEventListener(eventName, handler);')
                    .add('trackedListeners.push({ node, eventName, handler });')
                    .dedent()
                    .add('}');
      builder.add('function queueUpdate(changed) {')
                        .indent()
                        .add('if (!isMounted) return;')
                        .add('pendingChanges = { ...pendingChanges, ...changed };')
                        .add('if (batchScheduled) return;')
                        .add('batchScheduled = true;')
                        .add('queueMicrotask(() => {')
                            .indent()
                            .add('batchScheduled = false;')
                            .add('const changes = pendingChanges;')
                            .add('pendingChanges = {};')
                            .add('if (isDestroyed) return;')
                            .add('update(ctx, changes);')
                        .dedent()
                        .add('});')
                        .dedent()
                        .add('}');

  // 2. Paste the developer's original logic so it forms the lexical environment
  builder.add('// --- Developer Logic ---');

  // Prop bindings replace the removed `export let` statements, in declaration
  // order. `undefined` means "not provided", so the declared default applies.
  props.forEach(({ name, defaultValue }) => {
    builder.add(defaultValue === null
      ? `let ${name} = props.${name};`
      : `let ${name} = props.${name} !== undefined ? props.${name} : (${defaultValue});`);
  });

  if (astPayload.rawScript) {
    // Split by newline and add to builder to maintain proper indentation
            const interceptedScript = interceptAssignments(
                  astPayload.rawScript,
                  reactiveVars.map(decl => decl.name)
            );
            interceptedScript.split('\n').forEach(line => builder.add(line));
  }

  // Hydration: server-rendered initial state overrides the script-computed
  // values. Props always win (they are re-applied by the parent), so prop
  // bindings are never seeded. The hasOwnProperty + bracket access pattern
  // means a hostile `__proto__` key in the serialized state cannot pollute
  // Object.prototype.
  if (hydratable) {
    const seedableVars = reactiveVars.filter(decl => !decl.isProp);
    if (seedableVars.length > 0) {
      builder.add('\n// --- Initial State ---');
      builder.add("if (hydrate && state && typeof state === 'object' && !Array.isArray(state)) {")
            .indent();
      seedableVars.forEach((declaration) => {
        builder.add(`if (Object.prototype.hasOwnProperty.call(state, ${JSON.stringify(declaration.name)})) ${declaration.name} = state[${JSON.stringify(declaration.name)}];`);
      });
      builder.dedent()
            .add('}');
    }
  }

  // 3. Build the Context Object dynamically
  // We use getters so the create() function always reads the latest memory reference
  builder.add('\n// --- Framework Context ---');
  builder.add('const ctx = {')
        .indent();
  
  reactiveVars.forEach(decl => {
    builder.add(`get ${decl.name}() { return ${decl.name}; },`);
  });
  
  builder.dedent()
        .add('};');

  // 4. Inject the generated DOM create() function
  builder.add('\n// --- DOM Creation ---');
      const createCode = generateCreateFunction(astPayload.template, componentImports);

  // Component instances with reactive props live in factory-scope references
  // shared by create() (which assigns them) and update() (which reads them).
  const componentRefNames = collectComponentRefNames(astPayload.template, componentImports);
  componentRefNames.forEach((refName) => builder.add(`let ${refName} = null;`));
  if (componentRefNames.length > 0) builder.add('');

  createCode.split('\n').forEach(line => builder.add(line));

  // 4b. Inject the hydration adoption walk for hydratable modules.
  if (hydratable) {
    const hydrationCode = generateHydrationFunction(astPayload.template);
    hydrationCode.split('\n').forEach(line => builder.add(line));
  }

  // 5. Inject the generated Reactivity Engine update() function
  builder.add('\n// --- Reactivity Engine ---');
  const updateCode = generateUpdateFunction(astPayload.template);
  updateCode.split('\n').forEach(line => builder.add(line));

  // 6. Mount the component to the DOM. Hydration adopts the server-rendered
  // root instead of creating one and falls back to a full client mount when
  // the walk reports any mismatch.
  builder.add('\n// --- Initialization ---');
  if (!hydratable) {
    builder.add('const rootNode = create(ctx);')
          .add('const childComponents = rootNode.__wizzChildComponents;')
          .add('const listUpdates = rootNode.__wizzListUpdates;')
          .add('target.appendChild(rootNode);')
          .add('rootNode.__wizzMountChildren();');
  } else {
    builder.add('const rootNode = hydrate ? hydrateCreate(target, state) : create(ctx);')
          .add('if (!rootNode) return mountComponent(target, props);')
          .add('const childComponents = hydrate ? [] : rootNode.__wizzChildComponents;')
          .add('const listUpdates = hydrate ? [] : rootNode.__wizzListUpdates;')
          .add('if (!hydrate) {')
          .indent()
          .add('target.appendChild(rootNode);')
          .add('rootNode.__wizzMountChildren();')
          .dedent()
          .add('}');
  }

  const initialChanges = reactiveVars.map(decl => `${decl.name}: true`).join(', ');
      builder.add(`update(ctx, { ${initialChanges} });`)
        .add('isMounted = true;')
        .add('mountHooks.forEach((hook) => hook());');

  // 7. Return the public API (e.g., a way to unmount/destroy the component)
  builder.add('\nreturn {')
        .indent();

  if (props.length > 0) {
    // Receives new prop values from the parent. A missing key keeps the
    // current binding; an explicit `undefined` re-applies the declared
    // default, matching the mount-time contract. Values are compared with
    // Object.is so identical updates never rerender the child. The local
    // names use the reserved `__wizz` prefix, which prop names cannot use,
    // so a prop can never shadow the accumulator.
    builder.add('setProps(next) {')
          .indent()
          .add('if (isDestroyed) return;')
          .add('const __wizzChanges = {};');
    props.forEach(({ name, defaultValue }) => {
      builder.add(`if (${JSON.stringify(name)} in next) {`)
            .indent();
      if (defaultValue === null) {
        builder.add(`if (!Object.is(${name}, next.${name})) {`)
              .indent()
              .add(`${name} = next.${name};`)
              .add(`__wizzChanges.${name} = true;`)
              .dedent()
              .add('}');
      } else {
        builder.add(`const __wizzNext = next.${name} !== undefined ? next.${name} : (${defaultValue});`)
              .add(`if (!Object.is(${name}, __wizzNext)) {`)
              .indent()
              .add(`${name} = __wizzNext;`)
              .add(`__wizzChanges.${name} = true;`)
              .dedent()
              .add('}');
      }
      builder.dedent()
            .add('}');
    });
    builder.add('if (Object.keys(__wizzChanges).length > 0) queueUpdate(__wizzChanges);')
          .dedent()
          .add('},');
  }

  builder.add('destroy() {')
        .indent()
      .add('isDestroyed = true;')
      .add('destroyHooks.forEach((hook) => hook());')
      .add('childComponents.forEach((component) => component.destroy());')
      .add('trackedListeners.forEach(({ node, eventName, handler }) => node.removeEventListener(eventName, handler));')
        .add('target.removeChild(rootNode);')
        .dedent()
        .add('}')
        .dedent()
        .add('};');

  builder.dedent()
        .add('}');

  return builder.generate();
}

module.exports = { generateComponent };