const assert = require('node:assert/strict');
const test = require('node:test');
const { assignNodeIds } = require('../analyzer/idAssigner');
const { analyzeDependencies } = require('../analyzer/dependencyAnalyzer');
const { parseComponent } = require('../parser');
const { generateComponent } = require('./componentGenerator');
const { VERSIONS } = require('../version');

async function flushUpdates() {
  await new Promise((resolve) => setTimeout(resolve, 0));
}

function createDocument() {
  const elements = new Map();

  return {
    createElement(name) {
      return {
        name,
        attributes: {},
        childNodes: [],
        listeners: {},
        setAttribute(attributeName, value) {
          this.attributes[attributeName] = value;
          if (attributeName === 'data-wizz-id') {
            elements.set(`[data-wizz-id="${value}"]`, this);
          }
        },
        appendChild(node) {
          this.childNodes.push(node);
        },
        insertBefore(node, referenceNode) {
          const existingIndex = this.childNodes.indexOf(node);
          if (existingIndex !== -1) this.childNodes.splice(existingIndex, 1);
          const referenceIndex = this.childNodes.indexOf(referenceNode);
          this.childNodes.splice(referenceIndex === -1 ? this.childNodes.length : referenceIndex, 0, node);
        },
        removeChild(node) {
          this.childNodes.splice(this.childNodes.indexOf(node), 1);
        },
        addEventListener(eventName, listener) {
          this.listeners[eventName] = listener;
        },
        removeEventListener(eventName, listener) {
          if (this.listeners[eventName] === listener) delete this.listeners[eventName];
        },
        dispatchEvent(eventName) {
          this.listeners[eventName]?.({ type: eventName, target: this });
        }
      };
    },
    createTextNode(nodeValue) {
      return { nodeValue };
    },
    querySelector(selector) {
      return elements.get(selector) || null;
    }
  };
}

test('generates a mountable module from formatted component source', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(`
    <script>let count = 0;</script>
    <main><h1>Count: {count}</h1></main>
  `)));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = {
    childNodes: [],
    appendChild(node) {
      this.childNodes.push(node);
    },
    removeChild(node) {
      this.childNodes.splice(this.childNodes.indexOf(node), 1);
    }
  };
  const mountComponent = new Function(
    'document',
    `${source.replace('export default ', '')}\nreturn mountComponent;`
  )(document);

  const component = mountComponent(target);

  assert.equal(target.childNodes.length, 1);
  assert.equal(target.childNodes[0].name, 'main');
  assert.equal(target.childNodes[0].childNodes[0].name, 'h1');
  assert.equal(target.childNodes[0].childNodes[0].childNodes[1].nodeValue, '0');

  component.destroy();
  assert.deepEqual(target.childNodes, []);
});

test('emits an ES module default export and creates framework context getters', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; const title = "Total";</script><p>{count}</p>'
  )));
  const source = generateComponent(payload);

  assert.match(source, /^export default function mountComponent\(target\)/m);
  assert.match(source, /get count\(\) \{ return count; \}/);
  assert.doesNotMatch(source, /get title\(\)/);
});

test('stamps the version header as the first line of every generated module', () => {
  const generate = (template) => generateComponent(assignNodeIds(analyzeDependencies(parseComponent(template))));

  for (const source of [
    generate('<main><p>Static</p></main>'),
    generate("<script>import Counter from './Counter.wizz';</script><main><Counter /></main>")
  ]) {
    const header = source.split('\n')[0];
    const match = header.match(
      /^\/\/ Generated by Wizz (\d+\.\d+\.\d+) \(component syntax (\d+\.\d+\.\d+), generated output (\d+\.\d+\.\d+)\)\. Edits will be overwritten\.$/
    );

    assert.notEqual(match, null, `expected a version header, got: ${header}`);
    assert.equal(match[1], VERSIONS.compiler);
    assert.equal(match[2], VERSIONS.syntax);
    assert.equal(match[3], VERSIONS.output);
    assert.equal(source.split('\n').filter((line) => line.includes('Generated by Wizz')).length, 1);
  }
});

test('generated modules keep the output contract surface pinned to output 1.1.0', () => {
  // This is the concrete meaning of VERSIONS.output within its major version:
  // the module surface and teardown behavior generated modules guarantee.
  // Breaking any assertion here requires bumping VERSIONS.output and the
  // compiler major version, never a silent codegen change.
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0;</script><main><p>{count}</p></main>'
  )));
  const source = generateComponent(payload);

  assert.match(source, /export default function mountComponent\(target\) \{/);
  assert.match(source, /return \{\n    destroy\(\) \{/);
  assert.match(source, /target\.removeChild\(rootNode\);/);
  assert.match(source, /\.__wizzChildComponents = childComponents;/);
  assert.match(source, /\.__wizzMountChildren = \(\) => mountChildren\.forEach\(\(mount\) => mount\(\)\);/);
  assert.match(source, /\.__wizzListUpdates = listUpdates;/);
});

test('renders non-reactive constant expressions during creation', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>const title = "Total";</script><p>{title}</p>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = {
    childNodes: [],
    appendChild(node) {
      this.childNodes.push(node);
    },
    removeChild(node) {
      this.childNodes.splice(this.childNodes.indexOf(node), 1);
    }
  };
  const mountComponent = new Function(
    'document',
    `${source.replace('export default ', '')}\nreturn mountComponent;`
  )(document);

  mountComponent(target);

  assert.equal(target.childNodes[0].childNodes[0].nodeValue, 'Total');
});

test('intercepts reactive mutations in the emitted component script', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; function increment() { count += 1; }</script><p>{count}</p>'
  )));
  const source = generateComponent(payload);

  assert.match(source, /count \+= 1; queueUpdate\(\{ count: true \}\);/);
});

test('does not update before component initialization is complete', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let name = null; if (!name) { name = "Alice"; }</script><p>{name}</p>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = {
    childNodes: [],
    appendChild(node) {
      this.childNodes.push(node);
    },
    removeChild(node) {
      this.childNodes.splice(this.childNodes.indexOf(node), 1);
    }
  };
  const mountComponent = new Function(
    'document',
    `${source.replace('export default ', '')}\nreturn mountComponent;`
  )(document);

  assert.doesNotThrow(() => mountComponent(target));
  assert.equal(target.childNodes[0].childNodes[0].nodeValue, 'Alice');
});

test('binds explicit event directives to component-local handlers', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let clicks = 0; function increment() { clicks++; }</script><button on:click={increment}>Clicks: {clicks}</button>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = {
    childNodes: [],
    appendChild(node) {
      this.childNodes.push(node);
    },
    removeChild(node) {
      this.childNodes.splice(this.childNodes.indexOf(node), 1);
    }
  };
  const mountComponent = new Function(
    'document',
    `${source.replace('export default ', '')}\nreturn mountComponent;`
  )(document);

  mountComponent(target);
  const button = target.childNodes[0];
  button.dispatchEvent('click');
  await flushUpdates();

  assert.equal(button.attributes['on:click'], undefined);
  assert.equal(button.childNodes[1].nodeValue, '1');
});

test('updates dynamic attributes and properties when reactive state changes', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let name = "Ada"; let selected = 1; function applyChanges() { name = "Grace"; selected = 0; }</script><input value={name} checked={selected} aria-label={name} on:click={applyChanges} />'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = {
    childNodes: [],
    appendChild(node) { this.childNodes.push(node); },
    removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); }
  };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  const input = target.childNodes[0];
  assert.equal(input.value, 'Ada');
  assert.equal(input.checked, 1);
  assert.equal(input.attributes['aria-label'], 'Ada');
  input.dispatchEvent('click');
  await flushUpdates();
  assert.equal(input.value, 'Grace');
  assert.equal(input.checked, 0);
  assert.equal(input.attributes['aria-label'], 'Grace');
});

test('renders the selected conditional branch during mounting', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    "<script>const section = 'About';</script><main>{#if section === 'About'}<p>Shown</p>{:else}<p>Hidden</p>{/if}</main>"
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild() {} };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);
  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'Shown');
});

test('reconciles keyed each blocks by moving retained nodes and removing deleted nodes', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(`
    <script>
      let items = [{ id: 1, name: 'Ada' }, { id: 2, name: 'Grace' }];
      function reorder() { items = [{ id: 2, name: 'Grace Hopper' }, { id: 1, name: 'Ada' }]; }
      function removeFirst() { items = [{ id: 1, name: 'Ada' }]; }
    </script>
    <main><button on:click={reorder}>Reorder</button><button on:click={removeFirst}>Remove</button><ul>{#each items as item (item.id)}<li>{item.name}</li>{/each}</ul></main>
  `)));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild() {} };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  const main = target.childNodes[0];
  const list = main.childNodes[2];
  const firstItem = list.childNodes[0];
  const secondItem = list.childNodes[1];
  main.childNodes[0].dispatchEvent('click');
  await flushUpdates();

  assert.strictEqual(list.childNodes[0], secondItem);
  assert.strictEqual(list.childNodes[1], firstItem);
  assert.equal(list.childNodes[0].childNodes[0].nodeValue, 'Grace Hopper');
  main.childNodes[1].dispatchEvent('click');
  await flushUpdates();
  assert.deepEqual(list.childNodes.filter((node) => node.name === 'li'), [firstItem]);
});

test('rejects duplicate each block keys during mounting', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    "<script>let items = [{ id: 1 }, { id: 1 }];</script><ul>{#each items as item (item.id)}<li>{item.id}</li>{/each}</ul>"
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { appendChild() {} };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);

  assert.throws(() => mountComponent(target), /Each block keys must be unique\./);
});

test('renders keyless each blocks over primitive collections and updates them positionally', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    "<script>let list = ['one', 'two']; function rename() { list = ['uno', 'dos', 'tres']; } function shrink() { list = ['only']; }</script><main><button on:click={rename}>Rename</button><button on:click={shrink}>Shrink</button><ul>{#each list as item}<li>{item}</li>{/each}</ul></main>"
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild() {} };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  const list = target.childNodes[0].childNodes[2];
  const items = () => list.childNodes.filter((node) => node.name === 'li');
  const firstItem = items()[0];
  const secondItem = items()[1];

  assert.deepEqual(items().map((li) => li.childNodes[0].nodeValue), ['one', 'two']);

  target.childNodes[0].childNodes[0].dispatchEvent('click');
  await flushUpdates();
  assert.strictEqual(items()[0], firstItem);
  assert.strictEqual(items()[1], secondItem);
  assert.deepEqual(items().map((li) => li.childNodes[0].nodeValue), ['uno', 'dos', 'tres']);

  target.childNodes[0].childNodes[1].dispatchEvent('click');
  await flushUpdates();
  assert.strictEqual(items()[0], firstItem);
  assert.deepEqual(items().map((li) => li.childNodes[0].nodeValue), ['only']);
});

test('rejects each block bodies with multiple root elements', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>const items = [1, 2];</script><ul>{#each items as item}<li>{item}</li><li>extra</li>{/each}</ul>'
  )));

  assert.throws(() => generateComponent(payload), /Each blocks must contain exactly one root element\./);
});

test('batches multiple assignments in one event into a single scheduled update with merged flags', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let a = 1; let b = 2; function set() { a = 3; b = 4; }</script><main><p>{a}</p><p>{b}</p><button on:click={set}>Set</button></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild() {} };
  const scheduled = [];
  const mountComponent = new Function(
    'document',
    'queueMicrotask',
    `${source.replace('export default ', '')}\nreturn mountComponent;`
  )(document, (callback) => scheduled.push(callback));
  mountComponent(target);

  const main = target.childNodes[0];
  main.childNodes[2].dispatchEvent('click');

  assert.equal(scheduled.length, 1);
  scheduled[0]();
  assert.equal(main.childNodes[0].childNodes[0].nodeValue, '3');
  assert.equal(main.childNodes[1].childNodes[0].nodeValue, '4');
});

test('defers DOM updates until the scheduled batch runs', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; function increment() { count += 1; }</script><main><p>{count}</p><button on:click={increment}>Inc</button></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild() {} };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  const main = target.childNodes[0];
  main.childNodes[1].dispatchEvent('click');

  assert.equal(main.childNodes[0].childNodes[0].nodeValue, '0');
  await flushUpdates();
  assert.equal(main.childNodes[0].childNodes[0].nodeValue, '1');
});

test('destroy cancels a pending scheduled update', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; function increment() { count += 1; }</script><main><button on:click={increment}>Clicks: {count}</button></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); } };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  const component = mountComponent(target);

  const button = document.querySelector('[data-wizz-id="1"]');
  button.dispatchEvent('click');
  component.destroy();
  await flushUpdates();

  assert.deepEqual(target.childNodes, []);
  assert.equal(button.childNodes[1].nodeValue, '0');
});

test('emits lifecycle hook registration machinery', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>function init() {} onMount(init); function bye() {} onDestroy(bye);</script><main><p>Total</p></main>'
  )));
  const source = generateComponent(payload);

  assert.match(source, /function onMount\(hook\) \{ mountHooks\.push\(hook\); \}/);
  assert.match(source, /function onDestroy\(hook\) \{ destroyHooks\.push\(hook\); \}/);
  assert.match(source, /isMounted = true;\n  mountHooks\.forEach\(\(hook\) => hook\(\)\);/);
  assert.match(source, /isDestroyed = true;\n      destroyHooks\.forEach\(\(hook\) => hook\(\)\);/);
});

test('runs mount hooks after mounting with the DOM attached and reactive state available', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let status = "created"; function first() { target.mountLog = target.childNodes.length; } function initialize() { status = "mounted"; } onMount(first); onMount(initialize);</script><main><p>{status}</p></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); } };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  assert.equal(target.mountLog, 1);
  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'created');
  await flushUpdates();
  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'mounted');
});

test('intercepts state mutations inside inline arrow callbacks passed to hooks', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let status = "created"; onMount(() => { status = "ready"; });</script><main><p>{status}</p></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); } };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  mountComponent(target);

  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'created');
  await flushUpdates();
  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'ready');
});

test('runs destroy hooks before teardown and ignores their scheduled updates', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; function teardown() { target.destroyLog = target.childNodes.length; count += 1; } onDestroy(teardown);</script><main><button>Clicks: {count}</button></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); } };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  const component = mountComponent(target);
  const button = document.querySelector('[data-wizz-id="1"]');

  component.destroy();

  assert.equal(target.destroyLog, 1);
  assert.deepEqual(target.childNodes, []);
  await flushUpdates();
  assert.equal(button.childNodes[1].nodeValue, '0');
});

test('removes tracked event listeners when the component is destroyed', async () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    '<script>let count = 0; function increment() { count += 1; }</script><main><button on:click={increment}>Clicks: {count}</button></main>'
  )));
  const source = generateComponent(payload);
  const document = createDocument();
  const target = { childNodes: [], appendChild(node) { this.childNodes.push(node); }, removeChild(node) { this.childNodes.splice(this.childNodes.indexOf(node), 1); } };
  const mountComponent = new Function('document', `${source.replace('export default ', '')}\nreturn mountComponent;`)(document);
  const component = mountComponent(target);
  const button = document.querySelector('[data-wizz-id="1"]');

  button.dispatchEvent('click');
  await flushUpdates();
  assert.equal(button.childNodes[1].nodeValue, '1');
  assert.notEqual(button.listeners.click, undefined);

  component.destroy();
  assert.equal(button.listeners.click, undefined);

  button.dispatchEvent('click');
  await flushUpdates();
  assert.equal(button.childNodes[1].nodeValue, '1');
});

test('allows formatting whitespace around an each block root element', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    "<script>let items = [{ id: 1, name: 'Ada' }];</script><ul>\n  {#each items as item (item.id)}\n    <li>{item.name}</li>\n  {/each}\n</ul>"
  )));

  assert.doesNotThrow(() => generateComponent(payload));
});

test('emits top-level component imports and mounts imported self-closing components', () => {
  const payload = assignNodeIds(analyzeDependencies(parseComponent(
    "<script>import Counter from './Counter.wizz';</script><main><Counter /></main>"
  )));
  const source = generateComponent(payload);

  assert.match(source, /^import Counter from "\.\/Counter\.js";/m);
  assert.match(source, /mountChildren\.push\(\(\) => childComponents\.push\(Counter\(node_1\)\)\);/);
  assert.match(
    source,
    /target\.appendChild\(rootNode\);\n  rootNode\.__wizzMountChildren\(\);\n  update\(ctx, \{  \}\);/
  );
  assert.match(source, /childComponents\.forEach\(\(component\) => component\.destroy\(\)\);/);
  assert.doesNotMatch(source, /document\.createElement\("Counter"\)/);
});

test('rejects component attributes, children, and root-level component tags', () => {
  const generate = (template) => generateComponent(assignNodeIds(analyzeDependencies(parseComponent(template))));

  assert.throws(
    () => generate("<script>import Counter from './Counter.wizz';</script><main><Counter label=\"Count\" /></main>"),
    /Component <Counter> does not support attributes or children\./
  );
  assert.throws(
    () => generate("<script>import Counter from './Counter.wizz';</script><Counter />"),
    /Component <Counter> must be nested inside an element\./
  );
});