const assert = require('node:assert/strict');
const test = require('node:test');
const { assignNodeIds } = require('../analyzer/idAssigner');
const { analyzeDependencies } = require('../analyzer/dependencyAnalyzer');
const { parseComponent } = require('../parser');
const { generateServerComponent, assertServerRenderable, VOID_ELEMENTS } = require('./serverGenerator');
const { VERSIONS } = require('../version');

function analyze(source) {
  return assignNodeIds(analyzeDependencies(parseComponent(source)));
}

function generateServer(source) {
  return generateServerComponent(analyze(source));
}

// Executes the emitted ESM under CommonJS by stripping the two export forms
// and returning the module's public surface. Generated server modules never
// touch DOM APIs, so no document is needed here.
function loadServerModule(moduleSource) {
  const transformed = moduleSource
    .replace('export { __wizzSerializeInitialState as serializeInitialState };', '')
    .replace('export function renderComponent(', 'function renderComponent(');
  return new Function(`${transformed}\nreturn { renderComponent, __wizzSerializeInitialState };`)();
}

function renderSource(source, props = {}) {
  const moduleSource = generateServer(source);
  return { moduleSource, ...loadServerModule(moduleSource).renderComponent(props) };
}

test('renders static markup with whitespace and interpolation output preserved byte-for-byte', () => {
  const { html } = renderSource('<script>let count = 0;</script><main>\n  <h1>Counter</h1>\n  <button data-testid="btn">Clicks: {count}</button>\n</main>\n');

  assert.equal(html, '<main>\n  <h1>Counter</h1>\n  <button data-testid="btn" data-wizz-id="1">Clicks: <!-- -->0</button>\n</main>');
});

test('emits the server output header variant exactly once as the first line', () => {
  const moduleSource = generateServer('<p>Hi</p>');
  const headerPattern = /^\/\/ Generated by Wizz (\d+\.\d+\.\d+) \(component syntax (\d+\.\d+\.\d+), server output (\d+\.\d+\.\d+)\)\. Edits will be overwritten\.$/;
  const headerLines = moduleSource.split('\n').filter((line) => headerPattern.test(line));

  assert.equal(headerLines.length, 1);
  assert.match(moduleSource.split('\n')[0], headerPattern);
  assert.match(moduleSource.split('\n')[0], new RegExp(`Wizz ${VERSIONS.compiler} \\(component syntax ${VERSIONS.syntax.replace(/\./g, '\\.')}, server output ${VERSIONS.output.replace(/\./g, '\\.')}\\)`));
});

test('escapes text interpolation output including script injection payloads', () => {
  const { html } = renderSource(`<script>let name = '<img src=x onerror=alert(1)>';</script><p>{name}</p>`);

  assert.doesNotMatch(html, /<img/);
  assert.match(html, /&lt;img src=x onerror=alert\(1\)&gt;/);
});

test('escapes static text and static attribute values at compile time', () => {
  const { html } = renderSource(`<p title='Tom & "Jerry" <3'>Tom & Jerry</p>`);

  assert.match(html, /<p title="Tom &amp; &quot;Jerry&quot; &lt;3">Tom &amp; Jerry<\/p>/);
});

test('escapes dynamic attribute values including quote-breakout payloads', () => {
  const { html } = renderSource(`<script>let evil = '"><img src=x onerror=alert(1)>';</script><p data-x={evil}>ok</p>`);

  assert.doesNotMatch(html, /<img src=x/);
  assert.match(html, /data-x="&quot;&gt;&lt;img src=x onerror=alert\(1\)&gt;"/);
});

test('inserts an empty comment between adjacent text-like children only', () => {
  const { html } = renderSource('<script>let a = 1; let b = 2;</script><p>{a}{b}</p>');

  // One marker between the two expressions; none before the first or at
  // element boundaries, where the parser splits text runs on its own.
  assert.equal(html, '<p data-wizz-id="1">1<!-- -->2</p>');

  const { html: mixed } = renderSource('<script>let a = 1;</script><p>{a}<span>x</span>{a}</p>');
  assert.equal(mixed, '<p data-wizz-id="1">1<span>x</span>1</p>');
});

test('renders void elements without an end tag', () => {
  const { html } = renderSource('<main><br/><hr/><img src="a.png"/></main>');

  assert.equal(html, '<main><br><hr><img src="a.png"></main>');
});

test('renders bare attributes as empty values', () => {
  const { html } = renderSource('<input hidden required/>');

  assert.equal(html, '<input hidden="" required="">');
});

test('renders dynamic attributes with escaped values and boolean attributes truthy-only', () => {
  const { html: truthy } = renderSource(
    '<script>let flag = 1; let label = "Total";</script><button disabled={flag} class={label}>go</button>'
  );
  assert.equal(truthy, '<button disabled class="Total" data-wizz-id="1">go</button>');

  const { html: falsy } = renderSource(
    '<script>let flag = 0;</script><button disabled={flag}>go</button>'
  );
  assert.equal(falsy, '<button data-wizz-id="1">go</button>');
});

test('always renders a dynamic value attribute, even when empty', () => {
  const { html } = renderSource('<script>let text = "";</script><input value={text}/>');

  assert.equal(html, '<input value="" data-wizz-id="1">');
});

test('skips event directives in server output', () => {
  const { html } = renderSource('<script>function go() {}</script><button on:click={go}>go</button>');

  assert.equal(html, '<button>go</button>');
  assert.doesNotMatch(html, /on:click/);
});

test('carries data-wizz-id values from the analyzer into server markup', () => {
  const { html } = renderSource('<script>let count = 0;</script><main><p>static</p><p>{count}</p></main>');

  assert.match(html, /<p>\{?static/);
  assert.match(html, /<p data-wizz-id="1">/);
});

test('applies prop bindings with defaults, overrides, and missing values', () => {
  const source = '<script>export let label = "Guest"; export let count;</script><p>{label}: {count}</p>';
  const { html: defaults } = renderSource(source);
  assert.equal(defaults, '<p data-wizz-id="1">Guest<!-- -->: <!-- -->undefined</p>');

  const { html: overridden } = renderSource(source, { label: 'Ada', count: 3 });
  assert.equal(overridden, '<p data-wizz-id="1">Ada<!-- -->: <!-- -->3</p>');

  const { html: partial } = renderSource(source, { label: 'Grace' });
  assert.equal(partial, '<p data-wizz-id="1">Grace<!-- -->: <!-- -->undefined</p>');
});

test('renders const and let expressions identically during creation', () => {
  const { html } = renderSource('<script>let count = 2; const title = "Total";</script><p>{title}: {count}</p>');

  assert.equal(html, '<p data-wizz-id="1">Total<!-- -->: <!-- -->2</p>');
});

test('renders only the first root element and drops surrounding root-level nodes', () => {
  const { html } = renderSource('\n  <p>first</p>\n  <p>second</p>\n');

  assert.equal(html, '<p>first</p>');
});

test('is deterministic across repeated compiles', () => {
  const source = '<script>let count = 0;</script><main><p>{count}</p><input value={count}/></main>';
  const first = generateServer(source);
  const second = generateServer(source);

  assert.equal(first, second);
});

test('snapshots reactive let declarations but not props or consts', () => {
  const { state } = renderSource(
    '<script>export let label = "x"; let count = 1; const title = "t";</script><p>{count}</p>'
  );

  assert.deepEqual(state, { count: 1 });
});

test('serializes the initial state as a guarded wizz-state script', () => {
  const { moduleSource } = renderSource('<script>let count = 1;</script><p>{count}</p>');
  const mod = loadServerModule(moduleSource);

  assert.equal(
    mod.__wizzSerializeInitialState({ count: 1 }),
    '<script type="application/wizz-state">{"count":1}</script>'
  );
});

test('prevents script-tag breakout through the serialized state', () => {
  const mod = loadServerModule(generateServer('<script>let count = 1;</script><p>{count}</p>'));

  const serialized = mod.__wizzSerializeInitialState({ count: '</script><script>alert(1)</script>' });
  assert.doesNotMatch(serialized, /<\/script><script>/);
  assert.match(serialized, /\\u003c\/script>/);
  assert.deepEqual(JSON.parse(serialized.replace('<script type="application/wizz-state">', '').replace('</script>', '')), { count: '</script><script>alert(1)</script>' });
});

test('rejects non-object state in serializeInitialState', () => {
  const mod = loadServerModule(generateServer('<script>let count = 1;</script><p>{count}</p>'));

  assert.throws(() => mod.__wizzSerializeInitialState(null), TypeError);
  assert.throws(() => mod.__wizzSerializeInitialState([1, 2]), TypeError);
  assert.throws(() => mod.__wizzSerializeInitialState('x'), TypeError);
  assert.throws(() => mod.__wizzSerializeInitialState(undefined), TypeError);
});

test('does not intercept reactive assignments in the server script', () => {
  // The last top-level assignment is the value the template renders: without
  // interception there is no queueUpdate emission in the module source.
  const moduleSource = generateServer('<script>let count = 0; count = 5;</script><p>{count}</p>');

  assert.doesNotMatch(moduleSource, /queueUpdate/);
  const { html } = renderSource('<script>let count = 0; count = 5;</script><p>{count}</p>');
  assert.equal(html, '<p data-wizz-id="1">5</p>');
});

test('rejects a script that references browser globals at render time', () => {
  const { renderComponent } = loadServerModule(generateServer(
    '<script>let name = document.title;</script><p>{name}</p>'
  ));

  assert.throws(() => renderComponent(), /document is not defined/);
});

test('renders components without a script', () => {
  const { html, state } = renderSource('<main><p>Plain</p></main>');

  assert.equal(html, '<main><p>Plain</p></main>');
  assert.deepEqual(state, {});
});

test('renders lifecycle fixtures with hooks registered but not invoked', () => {
  const { html } = renderSource(`
<script>
  let status = "created";
  function initialize() { status = "mounted"; }
  onMount(initialize);
</script>
<main><p>{status}</p></main>`);

  assert.equal(html, '<main><p data-wizz-id="1">created</p></main>');
});

test('does not mutate the props object passed to renderComponent', () => {
  const props = { label: 'Ada' };
  const source = '<script>export let label = "Guest";</script><p>{label}</p>';

  renderSource(source, props);

  assert.deepEqual(props, { label: 'Ada' });
});

test('emits a self-contained module with no import statements', () => {
  const moduleSource = generateServer('<main><p>Plain</p></main>');

  assert.doesNotMatch(moduleSource, /^import /m);
});

test('rejects if blocks with a located diagnostic', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<main>{#if flag}<p>x</p>{/if}</main>')),
    /Server rendering does not support \{#if\} conditional blocks at 1:7\./
  );
});

test('rejects each blocks with a located diagnostic', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<main>{#each items as item}<p>x</p>{/each}</main>')),
    /Server rendering does not support \{#each\} blocks at 1:7\./
  );
});

test('rejects imported component tags with a located diagnostic', () => {
  assert.throws(
    () => assertServerRenderable(analyze(
      '<script>import Counter from "./Counter.wizz";</script><main><Counter /></main>'
    )),
    /Server rendering does not support component tags; <Counter> cannot be rendered server-side at 1:61\./
  );
});

test('rejects void elements carrying children', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<main><br>text</br></main>')),
    /Void element <br> cannot have children at 1:7\./
  );
});

test('validates event directives with the same messages as the browser target', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<script>function go() {}</script><main><button on:bad-name={go}>go</button></main>')),
    /Invalid event directive 'on:bad-name'\./
  );
  assert.throws(
    () => assertServerRenderable(analyze('<main><button on:click="">go</button></main>')),
    /Event directive 'on:click' requires a handler expression\./
  );
});

test('rejects unsafe reactive state names', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<script>let __proto__ = {};</script><main>x</main>')),
    /Reactive state name '__proto__' is not allowed in server-rendered components\./
  );
  assert.throws(
    () => assertServerRenderable(analyze('<script>let __wizzState = 1;</script><main>x</main>')),
    /Reactive state name '__wizzState' is not allowed in server-rendered components\./
  );
});

test('rejects templates without a root element', () => {
  assert.throws(
    () => assertServerRenderable(analyze('<script>let a = 1;</script>')),
    /Component template must contain a root element\./
  );
});

test('exposes the standard void-element set', () => {
  for (const tag of ['br', 'hr', 'img', 'input', 'meta', 'link']) {
    assert.ok(VOID_ELEMENTS.has(tag), `expected ${tag} in VOID_ELEMENTS`);
  }
  assert.ok(!VOID_ELEMENTS.has('div'));
});
