const assert = require('node:assert/strict');
const test = require('node:test');
const { compile, compileServer, VERSIONS } = require('./index');

function createDocument() {
  const elements = new Map();

  return {
    createElement(name) {
      return {
        name,
        attributes: {},
        childNodes: [],
        listeners: {},
        setAttribute(attributeName, value) {
          this.attributes[attributeName] = value;
          if (attributeName === 'data-wizz-id') {
            elements.set(`[data-wizz-id="${value}"]`, this);
          }
        },
        getAttribute(attributeName) {
          return this.attributes[attributeName] ?? null;
        },
        querySelector(selector) {
          for (const child of this.childNodes) {
            if (child.attributes?.['data-wizz-id'] && selector === `[data-wizz-id="${child.attributes['data-wizz-id']}"]`) return child;
            const match = child.querySelector?.(selector);
            if (match) return match;
          }
          return null;
        },
        appendChild(node) {
          this.childNodes.push(node);
        },
        addEventListener(eventName, listener) {
          this.listeners[eventName] = listener;
        },
        removeEventListener(eventName, listener) {
          if (this.listeners[eventName] === listener) delete this.listeners[eventName];
        },
        dispatchEvent(eventName) {
          this.listeners[eventName]?.({ type: eventName, target: this });
        }
      };
    },
    createTextNode(nodeValue) {
      return { nodeValue };
    },
    querySelector(selector) {
      return elements.get(selector) || null;
    }
  };
}

function mount(source, document) {
  const target = {
    childNodes: [],
    appendChild(node) {
      this.childNodes.push(node);
    },
    removeChild(node) {
      this.childNodes.splice(this.childNodes.indexOf(node), 1);
    }
  };
  const mountComponent = new Function(
    'document',
    `${compile(source).source.replace('export default ', '')}\nreturn mountComponent;`
  )(document);

  return { component: mountComponent(target), target };
}

test('exposes the frozen compatibility versions and stamps them into the module', () => {
  const { source, payload, version } = compile(
    '<script>let count = 0;</script><main><p>{count}</p></main>'
  );

  assert.deepEqual({ ...version }, { ...VERSIONS });
  assert.equal(Object.isFrozen(version), true);

  // The version lives on the compile result, never inside the internal payload.
  assert.equal('version' in payload, false);
  assert.match(source, /^\/\/ Generated by Wizz /m);
});

test('returns the generated module source and its analyzed payload', () => {
  const { source, payload, sourceMap } = compile(
    '<script>let count = 0; const title = "Total";</script><section><h1>{title}</h1><p>Count: {count + 1}</p></section>'
  );

  assert.match(source, /^export default function mountComponent\(target, props = \{\}\)/m);

  const section = payload.template.children[0];
  const heading = section.children[0];
  const paragraph = section.children[1];

  // Reactive declarations drive dependency tracking and context getters...
  assert.deepEqual(heading.children[0].dependencies, []);
  assert.deepEqual(paragraph.children[1].dependencies, ['count']);
  assert.match(source, /get count\(\) \{ return count; \}/);
  assert.doesNotMatch(source, /get title\(\)/);

  // ...and ID assignment targets only the element holding the reactive child.
  assert.equal(
    paragraph.attributes.find((attribute) => attribute.name === 'data-wizz-id')?.value,
    '1'
  );
  assert.equal(heading.attributes.find((attribute) => attribute.name === 'data-wizz-id'), undefined);
  assert.equal(sourceMap, null);
});

test('returns a source map for file-backed components with author script', () => {
  const componentSource = '<script>let count = 0;</script><p>{count}</p>';
  const { sourceMap } = compile(componentSource, { filePath: 'src/components/Counter.wizz' });

  assert.deepEqual(sourceMap.sources, ['src/components/Counter.wizz']);
  assert.deepEqual(sourceMap.sourcesContent, [componentSource]);
  assert.match(sourceMap.mappings, /EAAQ/);
});

test('emits intercepted mutations and targeted updates in the generated source', () => {
  const { source } = compile(
    '<script>let count = 0; function increment() { count += 1; }</script><button on:click={increment}>Clicks: {count}</button>'
  );

  assert.match(source, /count \+= 1; queueUpdate\(\{ count: true \}\);/);
  assert.match(source, /rootNode\.querySelector\('\[data-wizz-id="1"\]'\)/);
});

test('mounts, updates through events, and destroys against a minimal DOM', async () => {
  const document = createDocument();
  const { component, target } = mount(
    `
    <script>
      let count = 0;
      function increment() {
        count += 1;
      }
    </script>
    <main><button on:click={increment}>Clicks: {count}</button></main>
  `,
    document
  );

  const button = target.childNodes[0].childNodes[0];
  assert.equal(button.childNodes[1].nodeValue, '0');

  button.dispatchEvent('click');
  await new Promise((resolve) => setTimeout(resolve, 0));
  assert.equal(button.childNodes[1].nodeValue, '1');

  component.destroy();
  assert.deepEqual(target.childNodes, []);
});

test('compiles a static component without a script block', () => {
  const { source, payload } = compile('<main><p>Total</p></main>');

  assert.deepEqual(payload.script, []);
  assert.equal(payload.rawScript, '');
  assert.doesNotMatch(source, /data-wizz-id|querySelector/);

  const document = createDocument();
  const { target } = mount('<main><p>Total</p></main>', document);
  assert.equal(target.childNodes[0].childNodes[0].childNodes[0].nodeValue, 'Total');
});

test('propagates compiler errors with their component source locations', () => {
  assert.throws(() => compile('<main><p>{count}</p>'), /Unclosed tag <main> starting at 1:1\./);
  assert.throws(() => compile('<div></span>'), /Mismatched closing tag\. Expected <\/div>, found <\/span> at 1:6\./);
  assert.throws(() => compile('<p>{1 2}</p>'), /Template Expression Error at 1:7 - Unexpected token Number/);
});

test('identifies the input file and source location when compiling from a file', () => {
  const unclosed = (() => {
    try {
      compile('<main><p>{count}</p>', { filePath: 'src/pages/Home.wizz' });
    } catch (error) {
      return error;
    }
  })();

  assert.ok(unclosed instanceof SyntaxError);
  assert.equal(unclosed.filePath, 'src/pages/Home.wizz');
  assert.equal(unclosed.sourceExcerpt, '<main><p>{count}</p>');
  assert.equal(
    unclosed.codeFrame,
    'src/pages/Home.wizz:1:1\n1 | <main><p>{count}</p>\n  | ^'
  );
  assert.equal(
    unclosed.message,
    'Unclosed tag <main> starting at src/pages/Home.wizz:1:1.\n\n' +
      'src/pages/Home.wizz:1:1\n1 | <main><p>{count}</p>\n  | ^'
  );

  assert.throws(
    () => compile('<div></span>', { filePath: 'Home.wizz' }),
    /found <\/span> at Home\.wizz:1:6\./
  );
  assert.throws(
    () => compile('<p>{1 2}</p>', { filePath: 'Home.wizz' }),
    /Template Expression Error at Home\.wizz:1:7 - Unexpected token Number/
  );
  assert.throws(
    () => compile('Only text', { filePath: 'Home.wizz' }),
    /Home\.wizz: Component template must contain a root element\.$/
  );
});

test('leaves error messages unchanged when no file path is supplied', () => {
  assert.throws(() => compile('<main><p>{count}</p>'), /Unclosed tag <main> starting at 1:1\./);
});

test('rejects non-string component source', () => {
  assert.throws(() => compile(undefined), /Component source must be a string\./);
  assert.throws(() => compile(undefined, { filePath: 'Home.wizz' }), /Home\.wizz: Component source must be a string\.$/);
  assert.throws(() => compile(undefined, null), /Component source must be a string\./);
});

test('compileServer produces the self-contained HTML string module contract', () => {
  const { source, payload, sourceMap, version } = compileServer(
    '<script>let count = 0;</script><main><p>Count: {count}</p></main>'
  );

  // Named exports only: no default browser mount, no DOM API anywhere.
  assert.doesNotMatch(source, /export default/);
  assert.match(source, /export function renderComponent\(props = \{\}\)/);
  assert.match(source, /export \{ __wizzSerializeInitialState as serializeInitialState \};/);
  assert.doesNotMatch(source, /createElement|createTextNode|appendChild/);
  assert.match(source, /server output \d+\.\d+\.\d+/);

  // Server output is evaluated as an HTML string at request time, so no
  // source map is produced even for file-backed compiles.
  assert.equal(sourceMap, null);
  assert.deepEqual({ ...version }, { ...VERSIONS });
  assert.equal(payload.template.children[0].name, 'main');
});

test('compileServer renders HTML and serializes state without a DOM', () => {
  const { source } = compileServer(
    '<script>let count = 0; const label = "A & B";</script><main><p title={label}>Count: {count}</p></main>'
  );

  const module = new Function(
    `${source
      .replace('export function renderComponent(', 'function renderComponent(')
      .replace('export { __wizzSerializeInitialState as serializeInitialState };', '')
    }\nreturn { renderComponent, __wizzSerializeInitialState };`
  )();

  const { html, state } = module.renderComponent();
  // The dynamic attribute carries the analyzer's data-wizz-id for hydration.
  assert.equal(html, '<main><p title="A &amp; B" data-wizz-id="1">Count: <!-- -->0</p></main>');
  assert.deepEqual(state, { count: 0 });
  assert.equal(
    module.__wizzSerializeInitialState({ count: 5 }),
    '<script type="application/wizz-state">{"count":5}</script>'
  );
});

test('compileServer rejects the non-server-renderable surface with located errors', () => {
  // Blocks and each lists are server-renderable since milestone 14.
  const { source: ifSource } = compileServer('<main>{#if ready}<p>yes</p>{/if}</main>');
  assert.match(ifSource, /if \(ready\)/);
  const { source: eachSource } = compileServer('<main>{#each items as item}<p></p>{/each}</main>');
  assert.match(eachSource, /for \(const item of items\)/);

  // Component tags stay ineligible until the caller vouches for a child
  // server build through the componentServerRenderable option.
  assert.throws(
    () => compileServer('<script>\nimport Counter from "./Counter.wizz";\n</script><main><Counter /></main>'),
    /Server rendering does not support component tags; <Counter> cannot be rendered server-side at 3:16\./
  );
  assert.throws(
    () => compileServer('<main><p>1 + 2 = {1 2}</p></main>'),
    /Template Expression Error at 1:21/
  );
});

test('compileServer errors identify the input file when compiling from a file', () => {
  const error = (() => {
    try {
      compileServer(
        '<script>\nimport Counter from "./Counter.wizz";\n</script><main><Counter /></main>',
        { filePath: 'src/pages/Home.wizz' }
      );
    } catch (caught) {
      return caught;
    }
  })();

  assert.ok(error instanceof SyntaxError);
  assert.equal(error.filePath, 'src/pages/Home.wizz');
  assert.equal(
    error.message,
    'Server rendering does not support component tags; <Counter> cannot be rendered server-side at ' +
      'src/pages/Home.wizz:3:16. No server-renderable build was provided for this import.\n\n' +
      'src/pages/Home.wizz:3:16\n3 | </script><main><Counter /></main>\n  |                ^'
  );
});

test('the hydratable option exports hydrateComponent and gates the surface', () => {
  const { source } = compile(
    '<script>let count = 0;</script><main><p>Count: {count}</p></main>',
    { hydratable: true }
  );

  assert.match(source, /export default function mountComponent\(target, props = \{\}\)/);
  assert.match(source, /export function hydrateComponent\(target, props = \{\}, state = null\)/);

  // Blocks hydrate since nested hydration; the remaining gate is the
  // server-renderable component surface (vouched imports only).
  const { source: blockSource } = compile('<main>{#if ready}<p>yes</p>{/if}</main>', { hydratable: true });
  assert.match(blockSource, /if \(ready\) \{/);
  assert.throws(
    () => compile('<script>\nimport Counter from "./Counter.wizz";\n</script><main><Counter /></main>', { hydratable: true }),
    /Server rendering does not support component tags/
  );

  // Default compiles never carry the hydration surface.
  const { source: defaultSource } = compile(
    '<script>let count = 0;</script><main><p>Count: {count}</p></main>'
  );
  assert.doesNotMatch(defaultSource, /hydrateComponent|hydrateCreate/);
});
