const assert = require('node:assert/strict');
const test = require('node:test');
const { createSourceMap, encodeVlq } = require('./sourceMapGenerator');

test('encodes source map VLQ values', () => {
  assert.equal(encodeVlq(0), 'A');
  assert.equal(encodeVlq(1), 'C');
  assert.equal(encodeVlq(-1), 'D');
  assert.equal(encodeVlq(16), 'gB');
});

test('maps emitted author script lines to their component source coordinates', () => {
  const componentSource = '<script>\n  let count = 0;\n  function increment() { count += 1; }\n</script>\n<main>{count}</main>';
  const rawScript = '\n  let count = 0;\n  function increment() { count += 1; }\n';
  const generatedSource = [
    '// Generated by Wizz.',
    'export default function mountComponent(target) {',
    '  // --- Developer Logic ---',
    '  ',
    '    let count = 0;',
    '    function increment() { count += 1; }',
    '  ',
    '}'
  ].join('\n');

  const map = createSourceMap(componentSource, generatedSource, 'src/App.wizz', rawScript);

  assert.deepEqual(map, {
    version: 3,
    sources: ['src/App.wizz'],
    sourcesContent: [componentSource],
    names: [],
    mappings: ';;;EAAQ;EACR;EACA;EACA'
  });
});

test('does not create a map without a component path or copied author script', () => {
  assert.equal(createSourceMap('<main />', 'export default null;', '', ''), null);
  assert.equal(createSourceMap('<script>let count = 0;</script>', 'export default null;', 'App.wizz', 'let count = 0;'), null);
});

test('uses the script element instead of matching duplicate script text in the template', () => {
  const componentSource = '<p>let count = 0;</p>\n<script>let count = 0;</script>\n<main />';
  const generatedSource = '// --- Developer Logic ---\n  let count = 0;';

  const map = createSourceMap(componentSource, generatedSource, 'App.wizz', 'let count = 0;');

  assert.equal(map.mappings, ';EACQ');
});